$ENV{'TEXINPUTS'}=':' if length $ENV{'TEXINPUTS'} == 0;
$ENV{'TEXINPUTS'}='../../packages//:' . $ENV{'TEXINPUTS'}; 
$ENV{'TEXINPUTS'}='../../lyt//:' . $ENV{'TEXINPUTS'}; 
$pdflatex = "lualatex %O %S";

# vim:ft=perl
